db_base:
  image: neo4j/neo4j:stable
  environment:
    NEO4J_NO_AUTH: 1

db:
  extends:
    file: docker-compose.yml
    service: db_base
  ports:
    - "48461:7474"
  volumes:
    - ./db/neo4j/development/data:/data

db_test:
  extends:
    file: docker-compose.yml
    service: db_base
  ports:
    - "48462:7474"
  volumes:
    - ./db/neo4j/test/data:/data

web:
  build: .
  command: bin/rails s -b 0.0.0.0
  links:
    - db
    - db_test
  ports:
    - "48460:3000"
  volumes:
    - .:/usr/src/app
