db:
  extends:
    file: docker-compose.base.yml
    service: db_base
  ports:
    - "48461:7474"

db_test:
  extends:
    file: docker-compose.base.yml
    service: db_base
  ports:
    - "48462:7474"

web:
  build: .
  command: bin/guard -p -l 1
  links:
    - db
    - db_test
  ports:
    - "48460:3000"
  volumes:
    - .:/usr/src/app
  volumes_from:
    - gems
  stdin_open: true
  tty: true

gems:
  image: busybox
  volumes:
    - /ruby_gems
